services:
  backend:
    build: ./backend
    env_file: .env
    ports:
      - "8000:8000"
      - "5514:514/udp"
      - "5514:514/tcp"
    volumes:
      - data:/data
    restart: unless-stopped

  frontend:
    build: ./frontend
    environment:
      - VITE_API_BASE=${VITE_API_BASE-http://backend:8000}
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  data:
