name: build-and-push
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build Base (default edition). Also tag as plain :latest for convenience
      - name: Build & push Base
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            EDITION=base
          tags: |
            ghcr.io/catonacidd/logship-base:latest
            ghcr.io/catonacidd/logship:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # --- Enable later when Premium is ready ---
      # - name: Build & push Premium
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: .
      #     platforms: linux/amd64,linux/arm64
      #     push: true
      #     build-args: |
      #       EDITION=premium
      #     tags: |
      #       ghcr.io/catonacidd/logship-premium:latest
      #     cache-from: type=gha
      #     cache-to: type=gha,mode=max
